# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tahaluf' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tahaluf
  pod 'RealmSwift', '~> 10.49'
  pod 'ProgressHUD', '~> 14.1'

  target 'TahalufTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TahalufUITests' do
    # Pods for testing
  end

end
